openapi: 3.0.1
info:
  description: API Documentation
  license:
    name: GNU General Public License v3.0
    url: https://github.com/TheGamesDB/TheGamesDBv2/blob/master/LICENSE
  title: TheGamesDB API
  version: 2.0.0
servers:
- url: https://api.thegamesdb.net/
tags:
- name: Games
- name: Platforms
- name: Genres
- name: Developers
- name: Publishers
paths:
  /v1/Games/ByGameID:
    get:
      description: can request additional information can be requestes through `fields`
        and `include` params
      operationId: GamesByGameID
      parameters:
      - description: (Required)
        in: query
        name: apikey
        required: true
        schema:
          type: string
      - description: (Required) - supports `,` delimited list
        in: query
        name: id
        required: true
        schema:
          type: string
      - description: '(Optional) - valid `,` delimited options: `players`, `publishers`,
          `genres`, `overview`, `last_updated`, `rating`, `platform`, `coop`, `youtube`,
          `os`, `processor`, `ram`, `hdd`, `video`, `sound`, `alternates`'
        in: query
        name: fields
        schema:
          type: string
      - description: '(Optional) - valid `,` delimited options: `boxart`, `platform`'
        in: query
        name: include
        schema:
          type: string
      - description: (Optional) - results page offset to return
        in: query
        name: page
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamesByGameID'
          description: result
        400:
          content: {}
          description: bad input parameter
        403:
          content: {}
          description: bad API key or hit rate-limit cap
      summary: Fetch game(s) by id
      tags:
      - Games
  /v1/Games/ByGameName:
    get:
      description: can request additional information can be requestes through `fields`
        and `include` params
      operationId: GamesByGameName_v1
      parameters:
      - description: (Required)
        in: query
        name: apikey
        required: true
        schema:
          type: string
      - description: (Required) - Search term
        in: query
        name: name
        required: true
        schema:
          type: string
      - description: '(Optional) - valid `,` delimited options: `players`, `publishers`,
          `genres`, `overview`, `last_updated`, `rating`, `platform`, `coop`, `youtube`,
          `os`, `processor`, `ram`, `hdd`, `video`, `sound`, `alternates`'
        in: query
        name: fields
        schema:
          type: string
      - description: (Optional) - platform `id` can be obtain from the platforms api
          below, supports `,` delimited list
        in: query
        name: filter[platform]
        schema:
          type: string
      - description: '(Optional) - valid `,` delimited options: `boxart`, `platform`'
        in: query
        name: include
        schema:
          type: string
      - description: (Optional) - results page offset to return
        in: query
        name: page
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamesByGameID_v1'
          description: result
        400:
          content: {}
          description: bad input parameter
        403:
          content: {}
          description: bad API key or hit rate-limit cap
      summary: Fetch game(s) by name
      tags:
      - Games
  /v1.1/Games/ByGameName:
    get:
      description: can request additional information can be requestes through `fields`
        and `include` params
      operationId: GamesByGameName
      parameters:
      - description: (Required)
        in: query
        name: apikey
        required: true
        schema:
          type: string
      - description: (Required) - Search term
        in: query
        name: name
        required: true
        schema:
          type: string
      - description: '(Optional) - valid `,` delimited options: `players`, `publishers`,
          `genres`, `overview`, `last_updated`, `rating`, `platform`, `coop`, `youtube`,
          `os`, `processor`, `ram`, `hdd`, `video`, `sound`, `alternates`'
        in: query
        name: fields
        schema:
          type: string
      - description: (Optional) - platform `id` can be obtain from the platforms api
          below, supports `,` delimited list
        in: query
        name: filter[platform]
        schema:
          type: string
      - description: '(Optional) - valid `,` delimited options: `boxart`, `platform`'
        in: query
        name: include
        schema:
          type: string
      - description: (Optional) - results page offset to return
        in: query
        name: page
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamesByGameID'
          description: result
        400:
          content: {}
          description: bad input parameter
        403:
          content: {}
          description: bad API key or hit rate-limit cap
      summary: Fetch game(s) by name
      tags:
      - Games
  /v1/Games/ByPlatformID:
    get:
      description: can request additional information can be requested through `fields`
        and `include` params
      operationId: GamesByPlatformID
      parameters:
      - description: (Required)
        in: query
        name: apikey
        required: true
        schema:
          type: string
      - description: (Required) - platform `id` can be obtain from the platforms api
          below, supports `,` delimited list
        in: query
        name: id
        required: true
        schema:
          type: string
      - description: '(Optional) - valid `,` delimited options: `players`, `publishers`,
          `genres`, `overview`, `last_updated`, `rating`, `platform`, `coop`, `youtube`,
          `os`, `processor`, `ram`, `hdd`, `video`, `sound`, `alternates`'
        in: query
        name: fields
        schema:
          type: string
      - description: '(Optional) - valid `,` delimited options: `boxart`, `platform`'
        in: query
        name: include
        schema:
          type: string
      - description: (Optional) - results page offset to return
        in: query
        name: page
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamesByGameID'
          description: result
        400:
          content: {}
          description: bad input parameter
        403:
          content: {}
          description: bad API key or hit rate-limit cap
      summary: Fetch game(s) by platform id
      tags:
      - Games
  /v1/Games/Images:
    get:
      description: results can be filtered with `filter[type]` param
      operationId: GamesImages
      parameters:
      - description: (Required)
        in: query
        name: apikey
        required: true
        schema:
          type: string
      - description: (Required) - game(s) `id` can be obtain from the above games
          api, supports `,` delimited list
        in: query
        name: games_id
        required: true
        schema:
          type: string
      - description: '(Optional) - valid `,` delimited options: `fanart`, `banner`,
          `boxart`, `screenshot`, `clearlogo`'
        in: query
        name: filter[type]
        schema:
          type: string
      - description: (Optional) - results page offset to return
        in: query
        name: page
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamesImages'
          description: result
        400:
          content: {}
          description: bad input parameter
        403:
          content: {}
          description: bad API key or hit rate-limit cap
      summary: Fetch game(s) images by game(s) id
      tags:
      - Games
  /v1/Games/Updates:
    get:
      operationId: GamesUpdates
      parameters:
      - description: (Required)
        in: query
        name: apikey
        required: true
        schema:
          type: string
      - description: (Required)
        in: query
        name: last_edit_id
        required: true
        schema:
          type: integer
      - description: (Optional)
        in: query
        name: time
        schema:
          type: integer
      - description: (Optional) - results page offset to return
        in: query
        name: page
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamesUpdates'
          description: result
        400:
          content: {}
          description: bad input parameter
        403:
          content: {}
          description: bad API key or hit rate-limit cap
      summary: Fetch games update
      tags:
      - Games
  /v1/Platforms:
    get:
      operationId: Platforms
      parameters:
      - description: (Required)
        in: query
        name: apikey
        required: true
        schema:
          type: string
      - description: '(Optional) - valid `,` delimited options: `icon`, `console`,
          `controller`, `developer`, `manufacturer`, `media`, `cpu`, `memory`, `graphics`,
          `sound`, `maxcontrollers`, `display`, `overview`, `youtube`'
        in: query
        name: fields
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platforms'
          description: result
        400:
          content: {}
          description: bad input parameter
        403:
          content: {}
          description: bad API key or hit rate-limit cap
      summary: Fetch platforms list
      tags:
      - Platforms
  /v1/Platforms/ByPlatformID:
    get:
      operationId: PlatformsByPlatformID
      parameters:
      - description: (Required)
        in: query
        name: apikey
        required: true
        schema:
          type: string
      - description: (Required) - supports `,` delimited list
        in: query
        name: id
        required: true
        schema:
          type: integer
      - description: '(Optional) - valid `,` delimited options: `icon`, `console`,
          `controller`, `developer`, `manufacturer`, `media`, `cpu`, `memory`, `graphics`,
          `sound`, `maxcontrollers`, `display`, `overview`, `youtube`'
        in: query
        name: fields
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlatformsByPlatformID'
          description: result
        400:
          content: {}
          description: bad input parameter
        403:
          content: {}
          description: bad API key or hit rate-limit cap
      summary: Fetch platforms list by id
      tags:
      - Platforms
  /v1/Platforms/ByPlatformName:
    get:
      operationId: PlatformsByPlatformName
      parameters:
      - description: (Required)
        in: query
        name: apikey
        required: true
        schema:
          type: string
      - description: (Required)
        in: query
        name: name
        required: true
        schema:
          type: string
      - description: '(Optional) - valid `,` delimited options: `icon`, `console`,
          `controller`, `developer`, `manufacturer`, `media`, `cpu`, `memory`, `graphics`,
          `sound`, `maxcontrollers`, `display`, `overview`, `youtube`'
        in: query
        name: fields
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlatformsByPlatformName'
          description: result
        400:
          content: {}
          description: bad input parameter
        403:
          content: {}
          description: bad API key or hit rate-limit cap
      summary: Fetch platforms by name
      tags:
      - Platforms
  /v1/Platforms/Images:
    get:
      description: results can be filtered with `filter[type]` param
      operationId: PlatformsImages
      parameters:
      - description: (Required)
        in: query
        name: apikey
        required: true
        schema:
          type: string
      - description: (Required) - platform(s) `id` can be obtain from the above platforms
          api, supports `,` delimited list
        in: query
        name: platforms_id
        required: true
        schema:
          type: string
      - description: '(Optional) - valid `,` delimited options: `fanart`, `banner`,
          `boxart`'
        in: query
        name: filter[type]
        schema:
          type: string
      - description: (Optional) - results page offset to return
        in: query
        name: page
        schema:
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlatformsImages'
          description: result
        400:
          content: {}
          description: bad input parameter
        403:
          content: {}
          description: bad API key or hit rate-limit cap
      summary: Fetch platform(s) images by platform(s) id
      tags:
      - Platforms
  /v1/Genres:
    get:
      operationId: Genres
      parameters:
      - description: (Required)
        in: query
        name: apikey
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Genres'
          description: result
        400:
          content: {}
          description: bad input parameter
        403:
          content: {}
          description: bad API key or hit rate-limit cap
      summary: Fetch Genres list
      tags:
      - Genres
  /v1/Developers:
    get:
      operationId: Developers
      parameters:
      - description: (Required)
        in: query
        name: apikey
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Developers'
          description: result
        400:
          content: {}
          description: bad input parameter
        403:
          content: {}
          description: bad API key or hit rate-limit cap
      summary: Fetch Developers list
      tags:
      - Developers
  /v1/Publishers:
    get:
      operationId: Publishers
      parameters:
      - description: (Required)
        in: query
        name: apikey
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publishers'
          description: result
        400:
          content: {}
          description: bad input parameter
        403:
          content: {}
          description: bad API key or hit rate-limit cap
      summary: Fetch Publishers list
      tags:
      - Publishers
components:
  schemas:
    BaseApiResponse:
      example:
        code: 200
        status: Success
        remaining_monthly_allowance: 257
        extra_allowance: 0
      properties:
        code:
          minimum: 0
          type: integer
        status:
          type: string
        remaining_monthly_allowance:
          minimum: 0
          type: integer
        extra_allowance:
          minimum: 0
          type: integer
      required:
      - code
      - extra_allowance
      - remaining_monthly_allowance
      - status
      type: object
    PaginatedApiResponse:
      allOf:
      - $ref: '#/components/schemas/BaseApiResponse'
      - $ref: '#/components/schemas/PaginatedApiResponse_allOf'
    GamesByGameID:
      allOf:
      - $ref: '#/components/schemas/PaginatedApiResponse'
      - $ref: '#/components/schemas/GamesByGameID_allOf'
    GamesByGameID_v1:
      allOf:
      - $ref: '#/components/schemas/PaginatedApiResponse'
      - $ref: '#/components/schemas/GamesByGameID_v1_allOf'
    GamesImages:
      allOf:
      - $ref: '#/components/schemas/PaginatedApiResponse'
      - $ref: '#/components/schemas/GamesImages_allOf'
    GamesUpdates:
      allOf:
      - $ref: '#/components/schemas/PaginatedApiResponse'
      - $ref: '#/components/schemas/GamesUpdates_allOf'
    Platforms:
      allOf:
      - $ref: '#/components/schemas/BaseApiResponse'
      - $ref: '#/components/schemas/Platforms_allOf'
    PlatformsByPlatformID:
      allOf:
      - $ref: '#/components/schemas/BaseApiResponse'
      - $ref: '#/components/schemas/Platforms_allOf'
    PlatformsByPlatformName:
      allOf:
      - $ref: '#/components/schemas/BaseApiResponse'
      - $ref: '#/components/schemas/PlatformsByPlatformName_allOf'
    PlatformsImages:
      allOf:
      - $ref: '#/components/schemas/PaginatedApiResponse'
      - $ref: '#/components/schemas/PlatformsImages_allOf'
    Genres:
      allOf:
      - $ref: '#/components/schemas/BaseApiResponse'
      - $ref: '#/components/schemas/Genres_allOf'
    Developers:
      allOf:
      - $ref: '#/components/schemas/BaseApiResponse'
      - $ref: '#/components/schemas/Developers_allOf'
    Publishers:
      allOf:
      - $ref: '#/components/schemas/BaseApiResponse'
      - $ref: '#/components/schemas/Publishers_allOf'
    Publisher:
      example:
        id: 2374
        name: .GEARS Studios
      properties:
        id:
          minimum: 0
          type: integer
        name:
          type: string
      required:
      - id
      - name
      type: object
    Game:
      example:
        id: 4
        game_title: Star Fox 64
        release_date: 1997-06-30
        platform: 3
        players: 4
        overview: The Lylat system has been invaded!  Join Fox McCloud and his Star
          Fox team as they fight to save the galaxy from the clutches of the...
        last_updated: 2018-08-11 15:01:11
        rating: E - Everyone
        coop: No
        youtube: jsEcmfPwnHo
        developers:
        - 6037
        genres:
        - 1
        - 8
        publishers:
        - 3
        alternates:
        - Lylat Wars (EU)
        - Lylat Wars
      properties:
        id:
          minimum: 0
          type: integer
        game_title:
          type: string
        release_date:
          type: string
        platform:
          minimum: 0
          type: integer
        players:
          minimum: 0
          type: integer
        overview:
          type: string
        last_updated:
          type: string
        rating:
          type: string
        coop:
          type: string
        youtube:
          type: string
        os:
          type: string
        processor:
          type: string
        ram:
          type: string
        hdd:
          type: string
        video:
          type: string
        sound:
          type: string
        developers:
          items:
            minimum: 0
            type: integer
          type: array
        genres:
          items:
            minimum: 0
            type: integer
          type: array
        publishers:
          items:
            minimum: 0
            type: integer
          type: array
        alternates:
          items:
            type: string
          type: array
      type: object
    Platform:
      example:
        id: 25
        name: 3DO
        alias: 3do
        icon: 3do-1336524121.png
        console: 25.png
        controller: ""
        developer: The 3DO Company
      properties:
        id:
          minimum: 0
          type: integer
        name:
          type: string
        alias:
          type: string
        icon:
          type: string
        console:
          type: string
        controller:
          type: string
        developer:
          type: string
        overview:
          type: string
      required:
      - alias
      - console
      - controller
      - developer
      - icon
      - id
      - name
      type: object
    PlatformSkinny:
      example:
        id: 3
        name: Nintendo 64
        alias: nintendo-64
      properties:
        id:
          minimum: 0
          type: integer
        name:
          type: string
        alias:
          type: string
      required:
      - alias
      - id
      - name
      type: object
    ImageBaseUrlMeta:
      example:
        original: https://cdn.thegamsdb.net/images/original/
        small: https://cdn.thegamsdb.net/images/small/
        thumb: https://cdn.thegamsdb.net/images/thumb/
        cropped_center_thumb: https://cdn.thegamsdb.net/images/cropped_center_thumb/
        medium: https://cdn.thegamsdb.net/images/medium/
        large: https://cdn.thegamsdb.net/images/large/
      properties:
        original:
          type: string
        small:
          type: string
        thumb:
          type: string
        cropped_center_thumb:
          type: string
        medium:
          type: string
        large:
          type: string
      required:
      - cropped_center_thumb
      - large
      - medium
      - original
      - small
      - thumb
      type: object
    PlatformImage:
      example:
        id: 72
        type: fanart
        filename: platform/fanart/12-1.jpg
      properties:
        id:
          minimum: 0
          type: integer
        type:
          type: string
        filename:
          type: string
      type: object
    GameImage:
      example:
        id: 23413
        type: boxart
        side: front
        filename: boxart/front/1-1.jpg
        resolution: 1529x2156
      properties:
        id:
          minimum: 0
          type: integer
        type:
          type: string
        side:
          type: string
        filename:
          type: string
        resolution:
          type: string
      type: object
    UpdateModel:
      example:
        edit_id: 23159
        game_id: 60901
        timestamp: 2018-09-05 21:21:27
        type: boxart
        value: boxart/front/60901-1.jpg
      properties:
        edit_id:
          minimum: 0
          type: integer
        game_id:
          minimum: 0
          type: integer
        timestamp:
          type: string
        type:
          type: string
        value:
          type: string
      type: object
    Developer:
      example:
        id: 202
        name: Acclaim Studios Manchester
      properties:
        id:
          minimum: 0
          type: integer
        name:
          type: string
      required:
      - id
      - name
      type: object
    Genre:
      example:
        id: 1
        name: Action
      properties:
        id:
          minimum: 0
          type: integer
        name:
          type: string
      required:
      - id
      - name
      type: object
    PaginatedApiResponse_allOf_pages:
      example: '{"previous":"","current":"https://api.thegamesdb.net/Games/ByGameID?apikey=APIKEY&id=1%2C2%2C3%2C4&fields=players%2Cpublishers%2Cgenres%2Coverview%2Clast_updated%2Crating%2Cplatform%2Ccoop%2Cyoutube%2Cos%2Cprocessor%2Cram%2Chdd%2Cvideo%2Csound%2Calternates&include=boxart%2Cplatform&page=1","next":""}'
      properties:
        previous:
          type: string
        current:
          type: string
        next:
          type: string
      required:
      - current
      - next
      - previous
    PaginatedApiResponse_allOf:
      properties:
        pages:
          $ref: '#/components/schemas/PaginatedApiResponse_allOf_pages'
      required:
      - pages
    GamesByGameID_allOf_data:
      properties:
        count:
          minimum: 0
          type: integer
        games:
          items:
            $ref: '#/components/schemas/Game'
          type: array
      required:
      - count
      - games
    GamesByGameID_allOf_include_boxart:
      properties:
        base_url:
          $ref: '#/components/schemas/ImageBaseUrlMeta'
        data:
          additionalProperties:
            items:
              $ref: '#/components/schemas/GameImage'
            type: array
          type: object
      required:
      - base_url
      - data
    GamesByGameID_allOf_include_platform:
      properties:
        data:
          additionalProperties:
            $ref: '#/components/schemas/PlatformSkinny'
          type: object
      required:
      - data
    GamesByGameID_allOf_include:
      properties:
        boxart:
          $ref: '#/components/schemas/GamesByGameID_allOf_include_boxart'
        platform:
          $ref: '#/components/schemas/GamesByGameID_allOf_include_platform'
      required:
      - boxart
      - platform
    GamesByGameID_allOf:
      properties:
        data:
          $ref: '#/components/schemas/GamesByGameID_allOf_data'
        include:
          $ref: '#/components/schemas/GamesByGameID_allOf_include'
      required:
      - data
      - include
    GamesByGameID_v1_allOf_include:
      properties:
        boxart:
          $ref: '#/components/schemas/GamesByGameID_allOf_include_boxart'
        platform:
          additionalProperties:
            $ref: '#/components/schemas/PlatformSkinny'
          type: object
      required:
      - boxart
      - platform
    GamesByGameID_v1_allOf:
      properties:
        data:
          $ref: '#/components/schemas/GamesByGameID_allOf_data'
        include:
          $ref: '#/components/schemas/GamesByGameID_v1_allOf_include'
      required:
      - data
      - include
    GamesImages_allOf_data:
      properties:
        count:
          minimum: 0
          type: integer
        base_url:
          $ref: '#/components/schemas/ImageBaseUrlMeta'
        images:
          additionalProperties:
            items:
              $ref: '#/components/schemas/GameImage'
            type: array
          type: object
      required:
      - base_url
      - count
      - images
    GamesImages_allOf:
      properties:
        data:
          $ref: '#/components/schemas/GamesImages_allOf_data'
      required:
      - data
    GamesUpdates_allOf_data:
      properties:
        count:
          minimum: 0
          type: integer
        updates:
          items:
            $ref: '#/components/schemas/UpdateModel'
          type: array
      required:
      - count
      - updates
    GamesUpdates_allOf:
      properties:
        data:
          $ref: '#/components/schemas/GamesUpdates_allOf_data'
      required:
      - data
    Platforms_allOf_data:
      properties:
        count:
          minimum: 0
          type: integer
        platforms:
          additionalProperties:
            $ref: '#/components/schemas/Platform'
          type: object
      required:
      - count
      - platforms
    Platforms_allOf:
      properties:
        data:
          $ref: '#/components/schemas/Platforms_allOf_data'
      required:
      - data
    PlatformsByPlatformName_allOf_data:
      properties:
        count:
          minimum: 0
          type: integer
        platforms:
          items:
            $ref: '#/components/schemas/Platform'
          type: array
      required:
      - count
      - platforms
    PlatformsByPlatformName_allOf:
      properties:
        data:
          $ref: '#/components/schemas/PlatformsByPlatformName_allOf_data'
      required:
      - data
    PlatformsImages_allOf_data:
      properties:
        count:
          minimum: 0
          type: integer
        base_url:
          $ref: '#/components/schemas/ImageBaseUrlMeta'
        images:
          additionalProperties:
            items:
              $ref: '#/components/schemas/PlatformImage'
            type: array
          type: object
      required:
      - base_url
      - count
      - images
    PlatformsImages_allOf:
      properties:
        data:
          $ref: '#/components/schemas/PlatformsImages_allOf_data'
      required:
      - data
    Genres_allOf_data:
      properties:
        count:
          minimum: 0
          type: integer
        genres:
          additionalProperties:
            $ref: '#/components/schemas/Genre'
          type: object
      required:
      - count
      - genres
    Genres_allOf:
      properties:
        data:
          $ref: '#/components/schemas/Genres_allOf_data'
      required:
      - data
    Developers_allOf_data:
      properties:
        count:
          minimum: 0
          type: integer
        developers:
          additionalProperties:
            $ref: '#/components/schemas/Developer'
          type: object
      required:
      - count
      - developers
    Developers_allOf:
      properties:
        data:
          $ref: '#/components/schemas/Developers_allOf_data'
      required:
      - data
    Publishers_allOf_data:
      properties:
        count:
          minimum: 0
          type: integer
        publishers:
          additionalProperties:
            $ref: '#/components/schemas/Publisher'
          type: object
      required:
      - count
      - publishers
    Publishers_allOf:
      properties:
        data:
          $ref: '#/components/schemas/Publishers_allOf_data'
      required:
      - data
